FROM node:lts-alpine AS build

RUN apk update && \
    apk upgrade --available && \
    rm -rf /var/cache/apk/*

WORKDIR /app/
ENV PATH=/app/node_modules/.bin:$PATH

COPY ./front/package.json ./front/yarn.lock ./
RUN yarn install

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY ./front .
RUN yarn build


FROM nginx:stable-alpine

RUN apk update && \
    apk upgrade --available && \
    rm -rf /var/cache/apk/*

COPY --from=build /app/dist/ /usr/share/nginx/html/
COPY ./front/nginx.conf /etc/nginx/conf.d/default.conf
